### ISSUE TITLE
readme.mdの修正

### ISSUE THREAD

**Issue by TNTSuperMan** [tkc49/scratchblocks-for-wp#1]
readme.mdが少し打ち間違えています。
2行目、3行目がScratchBlcokとScratchBlockを間違っています。
ScratchBlockに修正してほしいです。

**Comment by tkc49** [comment]
@TNTSuperMan 

[#6bf57ac](https://github.com/tkc49/scratchblocks-for-wp/commit/6bf57ac75b4d155860ff8fb65629e6a45b2ebc31)

ありがとうございます！
修正をしました！
